# Generated by Django 3.0.4 on 2021-02-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdbtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_dob',
            field=models.DateField(),
        ),
        migrations.AlterModelTable(
            name='student',
            table='firstdbtest_student',
        ),
    ]
