# Generated by Django 3.0.4 on 2021-02-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdbtest', '0002_auto_20210219_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_dob',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
